name: expenditure
description: "Spend"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  firebase_core_platform_interface: ^6.0.0
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  firebase_database: ^11.3.9
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  google_sign_in: ^6.3.0
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  flutter_svg: ^2.2.0
  connectivity_plus: ^6.1.4
  device_info_plus: ^11.5.0
  flutter_device_type: ^0.4.0
  fluttertoast: ^8.2.12
  package_info_plus: ^8.3.0
  flutter_riverpod: ^3.0.0-dev.3
  collection: ^1.19.1
  flutter_keyboard_visibility: ^6.0.0
  syncfusion_flutter_datepicker: ^30.1.38

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  drift_dev: ^2.27.0
  flutter_lints: ^6.0.0



flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/icons/
    - assets/images/


